# Test your FastAPI endpoints

GET http://127.0.0.1:8080/
Accept: application/json

###

GET http://127.0.0.1:8080/health/hh
Accept: application/json

###

GET http://127.0.0.1:8080/health/users/20
Accept: application/json

###

POST http://127.0.0.1:8080/health/users/item
Content-Type: application/json

{
  "username": "1523456878",
  "password": "aaa123",
  "nickname": "Alsde"
}

###